# Ayu Dark - wezterm color config
# Scheme by [Your Name] (http://YOURWEBSITE.com)
[colors]
background = "#0A0E14"
foreground = "#B3B1AD"

# cursor_bg = "#0A0E14"
# cursor_border = "#B3B1AD"
# cursor_fg = "#0A0E14"

cursor_bg = '#F712FF'
cursor_border = '#37f499'
cursor_fg = '#FF0000'

selection_bg = "#B3B1AD"
selection_fg = "#0A0E14"

ansi = ["#0A0E14", "#FF3333", "#C2D94C", "#FF8F40", "#59C2FF", "#FFEE99", "#95E6CB", "#B3B1AD"]
brights = ["#4D5566", "#FF3333", "#C2D94C", "#FF8F40", "#59C2FF", "#FFEE99", "#95E6CB", "#B3B1AD"]

[metadata]
name = 'ayu_dark'
author = 'bwrc'
